sudo: false
language: python

cache:
    directories:
        - $HOME/.pip-cache/

python:
    - "3.6"
    - "3.7"

env:
    - DJANGO="Django>2"
    - DJANGO="https://github.com/django/django/archive/master.tar.gz"

install:
    - pip install --upgrade pip
    - pip install --cache-dir $HOME/.pip-cache -r requirements_debug.txt
    - pip install $DJANGO

script:
    - coverage run --source=. --omit="*/migrations/*" manage.py test
#   - pep8 --exclude="*/migrations/*",".ropeproject/*" --ignore=E501,W292,E265,E266,E402,E126 .

after_success:
    coveralls

matrix:
    exclude:
        - python: "3.6"
          env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
        - python: "3.7"
          env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
    allow_failures:
        - python: "3.6"
          env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
        - python: "3.7"
          env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
    fast_finish: true
